# Generated by Django 5.2.3 on 2025-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
