# Generated by Django 5.2.3 on 2025-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto', max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='Cantidad de productos en Inventario')),
                ('categoria', models.CharField(help_text='Categoría del producto (ej. Anillo, Collar, Pulsera)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del producto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha y hora de actualización del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
